### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by aacunha** [pitbulk/limesurvey-saml#2]
I configured the simplesamlphp and through the test url:
http://<limesurvey server>/simplesaml/module.php/core/authenticate.php
I can login via shibboleth iDP and after the login i can see the information about the user (cn, email, uid, etc)
But when i try to login through the plugin in limesurvey, after the iDP redirect back to limesurvey server, a get the "too many redirect" error.

**Comment by pitbulk** [comment]
Maybe session issue?

**Comment by aacunha** [comment]
In test page of simplesamlphp i can get the info and the attributes of session:

http://<Server_name>/simplesaml/module.php/core/authenticate.php?as=limesurvey

How can i get the info of the session in plugin or debug the procedure of login?

**Comment by pitbulk** [comment]
Add a debugger at the [newUserSession method](https://github.com/pitbulk/limesurvey-saml/blob/master/AuthSAML/AuthSAML.php#L188)

Also read:  
* https://code.google.com/p/simplesamlphp/wiki/LostState
* https://code.google.com/p/simplesamlphp/wiki/PHPSessions

If you use the memcache session handler in simpleSAMLphp the session issue gonna be out

**Comment by aacunha** [comment]
I solved the problem. Thanks for reply!

**Comment by pdomineaux** [comment]
@aacunha Can you tell us how do you fixed it? I'm facing the same problem.

**Comment by konstantinvlasenko** [comment]
Strangely enough, having this issue today. 
Nothing changed since initial configuration in August 2014. So it is definitely not a configuration issue for me. Maybe internet starts working differently ?:)
