### ISSUE TITLE
Issue with the login

### ISSUE THREAD

**Issue by ET1990** [pitbulk/limesurvey-saml#3]
**I have a problem with the login.**
When I try to login I am redirected to the adfs login page. I choose my domain, and then I am redirected back to the login page instead of the limesurvey admin page.

* I just want to say that simplesamlphp works well.

**Comment by pitbulk** [comment]
Can you install the SAMLTracer plugin on your Firefox browser and record your SAML flow.
I suggest that ADFS replies a SAMLResponse with a Status different than Success. (Also review ADFS logs if you can)

**Comment by ET1990** [comment]
I turn on the force login and now I get error massege in the simplesamlphp page:
"SimpleSAML_Error_NoState".

**Comment by pitbulk** [comment]
It is related to simpleSAMLphp:
https://simplesamlphp.org/docs/stable/simplesamlphp-nostate

**Comment by ET1990** [comment]
I do all the stuff they say and nothing work.
I still get the same error : "SimpleSAML_Error_NoState".
I dont now what to do .
