### ISSUE TITLE
using Remote Control despite SAML

### ISSUE THREAD

**Issue by bowerth** [pitbulk/limesurvey-saml#7]
hello,

Is it possible to use the remote control API despite using LS with SAML authentication?
I am navigating to LS using a redirect: `https://example.org/index.php?r=admin/survey/sa/listsurveys`

**Comment by Shnoulle** [comment]
I don't think it's possible currently : with API : you need username+password, since all action is done with redirect : i don't find a way for a plugin to authenticate.

Sometimes i think of a plugin with Auth `tokenkey` for API (like gitlab for example)

**Comment by pitbulk** [comment]
Can you elaborate what are you looking for?

As @Shnoulle mentioned, SAML flow requires to authenticate the user at the IdP side so I don't see how this can be integrated with an API call

**Comment by bowerth** [comment]
Thanks for your comments, I assume this can be closed.

**Comment by Shnoulle** [comment]
For information : https://gitlab.com/SondagesPro/Authentification/AuthRemoteToken was done for this.

user can generate dedicated token just for remote_control.
